mysite/myapp/urls.py
from django.urls import path

from myapp.views import alumno_view, aula_view, form_alumno, form_profesor, form_view, index_view, profesor_view

app_name = 'myapp'

urlpatterns = [
    path("", index_view.as_view(), name="onlyAuthor"),
    path("formulario/", form_view.as_view(), name="formulario"),
    path("formulario/<aula>/", aula_view, name="aula"),
    
    path("formAlum/", form_alumno.as_view(), name="formulario_alumno"),
    path("formAlum/<alumno>/", alumno_view, name="alumno"),

    path("formProf/", form_profesor.as_view(), name="formulario_profesor"),
    path("formProf/<profesor>/", profesor_view, name="profesor"),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from myapp.views import alumno_view, aula_view, form_alumno, form_profesor, form_view, index_view, profesor_view
from vitrina.views import BooksListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vitrina/', include('vitrina.urls')),
    path('myapp/', include('myapp.urls')),

]

mysite/vitrina/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page

from vitrina.views import BooksListView, pagina1, pagina2, select_book, author

app_name = 'vitrina'

urlpatterns = [
    path("book-list/", cache_page(60*1)(BooksListView.as_view()), name="booklist"),
    # path("book-list/", BooksListView.as_view(), name="booklist"),
    path("book/<id>/", select_book, name='select_book'),
    path("autor/<id>/", author, name='onlyAuthor'),
    path("pagina1/", pagina1, name='pagina1'),
    path("pagina2/", pagina2, name='pagina2'),
]

mysite/templates/author.html
{% extends 'base.html' %}

{% block contenido %}
<ul>
<li>{{author}}</li>
</ul>
{% endblock %}

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body{color:green}
    </style>
    
    <title>
        {% block titulo %} 
        {% endblock titulo %}
    </title>
</head>
<body>
    {% block contenido %}
    {% endblock contenido %}
</body>
</html>

mysite/templates/booklist.html
{% extends 'base.html' %}

{% block titulo %}
Lista de Libros
{% endblock titulo %}


{% block contenido %}

<h1>Lista de Libros</h1>
<ul>
    {% for libro in libros %}
    <div style='background-color:{% cycle 'lightblue' 'pink' 'yellow' 'coral' 'grey' %}'>
        <li>{{ forloop.counter0 }}</li>
        
        {% filter lower %}
        <li>{{ libro.title }}</li>
        {% endfilter %}
        
        
        {% if libro.authors|length <= 30 %}
        <li>{{ libro.authors|lower }}</li>
        <li>Tamaño del autor: {{ libro.authors|length }}</li>
        {% endif %}
            
    </div>
    <hr/>
    {% empty %}
    <li>No hay objetos.</li>
    {% endfor %}    
</ul>
{% endblock contenido %}

mysite/templates/form alumno.html
{% extends 'base.html' %}

{% block titulo %}
Formulario Alumno
{% endblock titulo %}
    

{% block contenido %}
<h1>Fomulario Alumno</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Enviar">
</form>
{% endblock contenido %}

mysite/templates/form profesor.html
{% extends 'base.html' %}

{% block titulo %}
Formulario Profesor
{% endblock titulo %}


{% block contenido %}
<h1>Fomulario Profesor</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Enviar">
</form>
{% endblock contenido %}

mysite/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario</title>
</head>
<body>
    <h1>Fomulario GET</h1>
    <form action="" method="get">
        {{ form }}
        <input type="submit" value="Enviar">
    </form>

    <h1>Fomulario POST</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Enviar">
    </form>
</body>
</html>

mysite/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Indice de Página</title>
</head>
<body>
    <h1>{{ name }} {{ last_name }}</h1>
    <h2>Mi edad es: {{ edad }}</h2>
</body>
</html>

mysite/templates/oneBook.html
{% extends 'base.html' %}

{% block contenido %}
<ul>

<li>{{book.title}}</li> 
<li><a href="{% url 'vitrina:onlyAuthor' book.id %}">{{book.authors}}</a></li>
<li>{{book.average_rating}}</li>
<li>{{book.isbn}}</li>
</ul>

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
{% endblock %}

mysite/templates/pagina1.html
{% extends 'base.html' %}

{% block contenido %}
<h1>{{ saludo }}</h1>
<h1>{{ sesion }}</h1>
<h1>{{ usuario }}</h1>
{% endblock contenido %}
    